config/urls.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.conf import settings
from django.conf.urls import include, url
from django.conf.urls.static import static
from django.contrib import admin
from django.views.generic import TemplateView, RedirectView
from symposion import views as symposion_views
from django.views import defaults as default_views
from . import views as o_views
from python_nigeria.core import views as core_views

urlpatterns = [
    # Examples:
    # url(r'^404$', TemplateView.as_view(template_name='500.html'), name='404'),
    # url(r'^blog/', include('blog.urls')),
    # url(r'^home/$', TemplateView.as_view(template_name='home.html'), name='home_page'),
    url(r"^design/home/$", core_views.DesignHomeView.as_view(), name="design_home"),
    url(r"^design/dashboard/$", core_views.DesignDashboardView.as_view(), name="design_dashboard_home"),
    url(r"^home/$", o_views.HomeRedirectView.as_view(), name="home_page"),
    # url(r'^schedule/$', o_views.ScheduleConferenceView.as_view(), name='schedule_conference'),
    url(r"^$", o_views.HomePage.as_view(), name="home"),
    url(r"^account/login/$", o_views.NewLoginView.as_view(), name="account_login"),
    url(
        r"^speaker/edit/(?:(?P<pk>\d+)/)?$",
        o_views.NewSpeakerEditView.as_view(),
        name="speaker_edit",
    ),
    url(r"^hijack/", include("hijack.urls")),
    url(r"^account/", include("account.urls")),
    url(r"^contact/", include("contact_form.urls")),
    # url(r'^captcha/', include('captcha.urls')),
    url(r"^we-are-allowed/", include(admin.site.urls)),
    url(r"^tickets/", include("python_nigeria.tickets.urls", namespace="tickets")),
    # url(r"^sponsorship/$", o_views.sponsors_view, name='sponsorship-proposal'),
]

if settings.DEBUG:
    # This allows the error pages to be debugged during development, just visit
    # these url in browser to see how these error pages look like.
    urlpatterns += [
        url(
            r"^400/$",
            default_views.bad_request,
            kwargs={"exception": Exception("Bad Request!")},
        ),
        url(
            r"^403/$",
            default_views.permission_denied,
            kwargs={"exception": Exception("Permission Denied")},
        ),
        url(
            r"^404/$",
            default_views.page_not_found,
            kwargs={"exception": Exception("Page not Found")},
        ),
        url(r"^500/$", default_views.server_error),
    ]
    import debug_toolbar

    urlpatterns += [url(r"^__debug__/", include(debug_toolbar.urls))]

urlpatterns += [
    # Your stuff: custom urls includes go here
    url(r"^dashboard/", o_views.dashboard, name="dashboard"),
    url(r"^proposals/", include("symposion.proposals.urls")),
    # url(r'^reviews/section/(?P<section_slug>[\w\-]+)/all/$', o_views.review_section, {"reviewed": "all"}, name="review_section"),
    url(r"^reviews/", include("symposion.reviews.urls")),
    url(r"^schedule/", include("symposion.schedule.urls")),
    url(r"^speaker/", include("symposion.speakers.urls")),
    url(r"^sponsors$", o_views.sponsors_list,name="sponsor_list"),
    url(r"^sponsors/apply", o_views.sponsor_apply, name="sponsor_apply"),
    url(r"^sponsors/", include("config.schedule_urls")),
    url(r"^teams/", include("symposion.teams.urls")),
    url(r"^boxes/", include("pinax.boxes.urls")),
    url(
        r"^blog/manage/posts/create/$",
        o_views.ManageCreatePost.as_view(),
        name="manage_post_create",
    ),
    url(
        r"^blog/manage/posts/(?P<post_pk>\d+)/update/$",
        o_views.ManageUpdatePost.as_view(),
        name="manage_post_update",
    ),
    url(r"^blog/", include("pinax.blog.urls", namespace="pinax_blog")),
    url(r"^", include("pinax.pages.urls")),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

python_nigeria/core/urls.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals
from django.views.decorators.csrf import csrf_exempt
import pytz
from django.conf.urls import include, url

from . import views

urlpatterns = [
    url(regex=r'online-payment/(?P<tutor_slug>[\w.@+-]+)/(?P<slug>[\w.@+-]+)/$',
        view=views.OnlinePaymentRedirectView.as_view(),
        name='dollar_online_payment'),
    url(regex=r'client-payment-completed/(?P<order>[\w.@+-]+)/$',
        view=csrf_exempt(views.ClientPaymentCompletedView.as_view()),
        name='request_complete_redirect'),
    url(regex=r'client-payment-cancelled/(?P<order>[\w.@+-]+)/$',
        view=csrf_exempt(views.FailedPaymentRedirectView.as_view()),
        name='request_cancelled_redirect'),
]

python_nigeria/tickets/urls.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.views.decorators.csrf import csrf_exempt
from django.conf import settings
from django.conf.urls import include, url
from django.contrib.auth.decorators import login_required
from . import views

urlpatterns = [
    # Examples:
    # url(r'^404$', TemplateView.as_view(template_name='500.html'), name='404'),
    # url(r'^blog/', include('blog.urls')),
    url(r"^$", views.TicketHomeView.as_view(), name="home"),
    url(r"^selected-plan$", views.intermediate_purchase, name="selected-plan"),
    url(r"^coupons$", views.valid_coupons, name="coupons"),
    url(
        r"^purchase/$",
        login_required(csrf_exempt(views.PurchaseView.as_view())),
        name="purchase",
    ),
    url(
        r"^purchase-complete/(?P<order>[\w.@+-]+)/$",
        login_required(views.purchase_complete),
        name="purchase-complete",
    ),
    # url(r'^checkout/(?P<order>[\w.@+-]+)/$', views.CheckoutView.as_view(), name='checkout_view'),
    # url(r'^checkout/(?P<order>[\w.@+-]+)/$', login_required(views.CheckoutView.as_view()), name='checkout_view'),
    url(
        r"^detail/(?P<order>[\w.@+-]+)/$",
        login_required(views.TicketDetailPage.as_view()),
        name="detail",
    ),
    url(
        r"^create/(?P<order>[\w.@+-]+)/$",
        login_required(views.CreateTicketview.as_view()),
        name="create_ticket",
    ),
    url(
        r"^sales/(?P<pk>\d+)/$",
        login_required(views.SalesTicketView.as_view()),
        name="sales",
    ),
    url(
        r"^paystack/webhook",
        view=csrf_exempt(views.paystack_webhook),
        name="p_stack_webhook",
    ),
    url(
        r"^paystack/callback/$",
        view=csrf_exempt(views.paystack_webhook),
        name="p_stack_callback",
    ),
    url(
        r"^paystack/callback/(?P<order>[\w.@+-]+)/$",
        view=csrf_exempt(views.PaystackCallBackView.as_view()),
        name="callback_paystack",
    ),
    url(
        r"^paystack/validate/(?P<order>[\w.@+-]+)/(?P<code>[\w.@+-]+)$",
        view=login_required(views.validate_paystack_ref),
        name="validate_paystack",
    ),
]

python_nigeria/core/models.py
from django.db import models
from symposion.sponsorship.models import Sponsor
class SponsorImage(models.Model):
    sponsor = models.OneToOneField(Sponsor, related_name='image_link')
    image = models.ImageField(upload_to="sponsors")

python_nigeria/proposals/models.py
from django.db import models
from django.utils.translation import ugettext_lazy as _
from markitup.fields import MarkupField
from symposion.proposals.models import ProposalBase


class Proposal(ProposalBase):

    AUDIENCE_LEVEL_NOVICE = 1
    AUDIENCE_LEVEL_EXPERIENCED = 2
    AUDIENCE_LEVEL_INTERMEDIATE = 3
    AUDIENCE_LEVEL_NOT_APPLICABLE = 4

    AUDIENCE_LEVELS = [
        (AUDIENCE_LEVEL_NOVICE, "Novice"),
        (AUDIENCE_LEVEL_INTERMEDIATE, "Intermediate or Advanced"),
        # (AUDIENCE_LEVEL_EXPERIENCED, "Experienced"),
        (AUDIENCE_LEVEL_NOT_APPLICABLE, "Not Applicable"),
    ]

    audience_level = models.IntegerField(choices=AUDIENCE_LEVELS)

    recording_release = models.BooleanField(
        default=True,
        help_text=_("By submitting your talk proposal, you agree to give "
                    "permission to the conference organizers to record, edit, "
                    "and release audio and/or video of your presentation. If "
                    "you do not agree to this, please uncheck this box."),
    )

    special_requirements = MarkupField(
        _("Special Requirements"),
        blank=True,
        help_text=_("If you have any special requirements such as needing "
                    "travel assistance, accessibility needs, or anything "
                    "else please let us know here so that  we may plan "
                    "accordingly. (This is not made public nor will the "
                    "review committee have access to view it.)")
    )

    class Meta:
        abstract = True

    def __unicode__(self):
        return u"%s" % self.title


class TalkProposal(Proposal):
    pass


class TutorialProposal(Proposal):
   pass


class OpenSpaceProposal(ProposalBase):
    pass

python_nigeria/proposals/forms.py
from django import forms
from markitup.widgets import MarkItUpWidget

from .models import OpenSpaceProposal, TalkProposal, TutorialProposal


class ProposalForm(forms.ModelForm):

    def clean_description(self):
        value = self.cleaned_data["description"]
        if len(value) > 400:
            raise forms.ValidationError(
                u"The description must be less than 400 characters"
            )
        return value

    def __init__(self, *args, **kwargs):
        super(ProposalForm, self).__init__(*args, **kwargs)
        for f in self.fields.values():
            if not f.required:
                continue
            f.widget.attrs.setdefault('required', True)
            f.label = '{} *'.format(f.label)


class OpenSpaceProposalForm(ProposalForm):

    class Meta:
        model = OpenSpaceProposal
        fields = [
            "title",
            "description",
            "abstract",
            "additional_notes",
        ]
        widgets = {
            "abstract": MarkItUpWidget(),
            "additional_notes": MarkItUpWidget(),
        }


class TalkProposalForm(ProposalForm):

    class Meta:
        model = TalkProposal
        fields = [
            "title",
            "audience_level",
            "description",
            "abstract",
            "additional_notes",
            "special_requirements",
            "recording_release",
        ]
        widgets = {
            "abstract": MarkItUpWidget(),
            "additional_notes": MarkItUpWidget(),
        }


class TutorialProposalForm(ProposalForm):

    class Meta:
        model = TutorialProposal
        fields = [
            "title",
            "audience_level",
            "description",
            "abstract",
            "additional_notes",
            "special_requirements",
            "recording_release",
        ]
        widgets = {
            "abstract": MarkItUpWidget(),
            "additional_notes": MarkItUpWidget(),
        }

python_nigeria/core/views.py
from django.contrib import messages
from django.views.generic import (
    FormView, RedirectView,
    TemplateView)
from config.utils import PayStack
import logging

logger = logging.getLogger(__name__)


class DesignDashboardView(TemplateView):
    template_name = "design/dashboard.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        return context


class DesignHomeView(TemplateView):
    template_name = "design/home.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context.update({
            'page_title': 'PyCon Nigeria 2025',
            'nav_items': [
                {'title': 'Home', 'url': '/', 'active': True},
                {'title': 'About', 'url': '/about/', 'has_dropdown': True},
                {'title': 'Schedule', 'url': '/schedule/', 'has_dropdown': True},
                {'title': 'Tickets', 'url': '/tickets/'},
                {'title': 'Contact', 'url': '/contact/'},
                {'title': 'Login', 'url': '/account/login/'},
            ]
        })
        return context


class OnlinePaymentRedirectView(RedirectView):
    permanent = False
    query_string = True

    def get_redirect_url(self, *args, **kwargs):
        try:
            req = services.SingleRequestService(slug=kwargs['slug'])
            url = req.create_online_booking(kwargs['tutor_slug'])
        except ObjectDoesNotExist:
            raise Http404('No Request matches the given query.')
        user = self.login_user(req.get_user())
        booking_url = "%s" % (reverse('request_payment_page', args=[url]),)

        if user is not None:
            return booking_url
        if self.request.user.is_authenticated():
            return booking_url
        return "%s?redirect_url=%s" % (reverse('account_login'), booking_url)

    def login_user(self, user):
        # log in the user
        user.backend = 'django.contrib.auth.backends.ModelBackend'
        login(self.request, user)
        return user


class ClientPaymentCompletedView(RedirectView):
    permanent = False
    query_string = True
    #

    def get_redirect_url(self, *args, **kwargs):
        status, message_txt = services.DepositMoneyService.generic_payment_outcome(
            self.request, **kwargs
        )
        if status:
            messages.info(self.request, message_txt)
            return reverse("users:revenue_transactions")
        messages.error(self.request, message_txt)
        return reverse("request_payment_page", args=[kwargs['order']])


class FailedPaymentRedirectView(RedirectView):
    permanent = False
    query_string = True

    def get_redirect_url(self, *args, **kwargs):
        print(self.request.POST)
        messages.error(self.request, "Sorry the payment was cancelled")
        return reverse('request_payment_page', args=[kwargs['order']])


class PaystackCallBackView(RedirectView):
    permanent = False
    query_string = True

    def get_redirect_url(self, *args, **kwargs):
        x = self.request.POST
        logger.info(x)
        print(x)
        y = self.request.GET.get('trxref')
        if y:
            v = utils.PayStack().validate_transaction(y)
            if v:
                try:
                    d = services.DepositMoneyService(kwargs.get('order'))
                    d.notify_admin_of_payments_made(condition=True, **v)
                    messages.info(
                        self.request, "Transaction Payment Successful!")
                    return reverse('users:revenue_transactions')
                except ObjectDoesNotExist:
                    d = services.SingleRequestService(kwargs.get('order'))
                    d.pay_processing_fee()
                    messages.info(
                        self.request, "Processing Fee Payment Successful!")
                    return reverse('processing_fee_completed', args=[kwargs.get('order')])
        messages.error(
            self.request, "Sorry there was an error in this transaction. contact info@tuteria.com")
        return reverse('request_payment_page', args=[kwargs.get('order')])

python_nigeria/templates/pinax/blog/blog_base.html
{% extends "site_base.html" %}

{% load pinax_blog_tags %}
{% load static from staticfiles %}
{% block stylings %}
<style>
  img{
    width: 100%;
  }
  .nav.navigation{
    display: flex;
    justify-content: space-around;
  }
  .post h2 a{
    color: #008751;
  }
  .post{
    margin-bottom: 20px;
    border-bottom: 2px solid #F2f2f2;
  }
  .post .body-content{
    margin-bottom: 45px;
  }
  .blog-header{
    height: 130px;
  }
</style>
{% endblock stylings %}
{% block body_class %}blog{% endblock %}

{% block body %}

<div class="blog-header poster-wrapper ">
  <h1>{% if post.title %}{{ post.title }}{% else %}Blog{% endif %} </h1>
</div>

<div class="poster-wrapper">
  <div class="container">
    <div class="row">

        <div class="col-md-10 col-md-offset-2">
          {% block content %}{% endblock %}
        </div>
    </div>
  </div>
</div>
{% endblock %}


{% comment %}
        <div class="col-md-3">

          {% block sidebar %}
            {% comment %}
            <div class="card">
              <div class="card-block">
                <h4 class="card-title">Blog lorem ipsum</h4>
              </div>
              <div class="card-block">
                <p class="card-text">Some quick example text to build on the card title and make up the bulk of the card's content.</p>
                <a href="#" class="card-link">Card link</a>
                <a href="#" class="card-link">Another link</a>
              </div>
            </div>
            <div class="search">
              {% if current_section == "all" %}
                {% url "pinax_blog:blog" as search_url %}
              {% else %}
                {% url "pinax_blog:blog_section" current_section.slug as search_url %}
              {% endif %}

              <form class="form-search" action="{{ search_url }}">
                <label><i class="fa fa-search"></i></label>
                <input class="form-control" type="search" placeholder="Search..." name="q" value="{{ search_term|default:"" }}">
              </form>
            </div>

            <div class="card blog-categories">
              <div class="card-header">
                <h4 class="card-title">Categories</h4>
              </div>
              <div class="card-block">
                <ul>
                  <li class="{% if current_section == "all" %}active{% endif %}">
                    <a href="{% url "pinax_blog:blog" %}">All</a>
                  </li>
                  {% blog_sections as sections %}
                  {% for section in sections %}
                    <li class="{% if current_section == section %}active{% endif %}">
                      <a href="{% url "pinax_blog:blog_section" section.slug %}">{{ section.name }}</a>
                    </li>
                  {% endfor %}
                </ul>
            </div>
          </div>

          <p>
            <a href="{% url 'pinax_blog:blog_feed' 'all' 'atom' %}"><i class="fa fa-rss"></i> Atom Feed</a>
          </p>

          {% endblock %}
        </div>
        {% endcomment %}

python_nigeria/templates/pinax/blog/blog_list.html
{% extends "pinax/blog/blog_base.html" %}

{% block head_title_base %}{{ SITE_NAME }}{% endblock %}

{% block content %}
  {% if post_list %}
    <div class="post-list">
      {% for post in post_list %}
        <div class="post">          
          <h2><a href="{{ post.get_absolute_url }}">{{ post.title }}</a></h2>
          {% include "pinax/blog/dateline.html" %}
          <div class="teaser">{{ post.teaser_html|safe }}</div>
          <!--<p class="more"><a href="{{ post.get_absolute_url }}" class="post-link">read more...</a></p>-->
          <div class="body-content"> {{post.content_html|safe}} </div>
        </div>
      {% endfor %}
    </div>
    {% include "pinax/pagination/builtin_pagination_reverse.html" %}
  {% else %}
    <p class="alert alert-info lead">No blog posts have been published.</p>
  {% endif %}
{% endblock %}

python_nigeria/templates/pinax/blog/blog_post.html
{% extends "pinax/blog/blog_base.html" %}
{% block stylings %}
{{block.super}}
<style>
.post{
    border-bottom: 0;
  }
  .blog-post{
      padding: 0;
  }
</style>
  
{% endblock stylings %}
{% block body_class %}blog blog-post{% endblock %}

{% block head_title_base %}{{ post.title }} | {{ SITE_NAME }}{% endblock %}

{% block extra_head %}
    {{ block.super }}
    <meta name="twitter:card" content="summary">
    {% comment %}
    <meta name="twitter:image" content="https://pbs.twimg.com/profile_images/62846141/pinaxproject_avatar.png">
    {% endcomment %}
    <meta property="og:title" content="{{ post.title }}">
    {% if post.description %}
        <meta name="description" content="{{ post.description }}">
        <meta property="og:description" content="{{ post.description }}">
    {% else %}
        <meta name="description" content="{{ post.teaser_html|striptags }}">
        <meta property="og:description" content="{{ post.teaser_html|striptags }}">
    {% endif %}
    {% if post.primary_image %}
        <meta property="og:image" content="http://{{ SITE_DOMAIN }}{{ post.primary_image.image_path.url }}">
    {% else %}
        {% comment %}
        <meta property="og:image" content="https://pbs.twimg.com/profile_images/62846141/pinaxproject_avatar.png">
        {% endcomment %}
    {% endif %}
    <meta property="og:url" content="http://{{ SITE_DOMAIN }}{{ post.get_absolute_url }}">
    <meta property="og:type" content="article">
{% endblock %}

{% block content %}
    <div class="post-detail">
        <div class="post">

            {% include "pinax/blog/dateline_stale.html" %}

            <div class="teaser">{{ post.teaser_html|safe }}</div>

            <div class="content">{{ post.content_html|safe }}</div>

            <div class="twitter-button">
                <a href="https://twitter.com/share" class="twitter-share-button" data-via="">Tweet</a>
                <script>!function(d,s,id){var js,fjs=d.getElementsByTagName(s)[0];if(!d.getElementById(id)){js=d.createElement(s);js.id=id;js.src="//platform.twitter.com/widgets.js";fjs.parentNode.insertBefore(js,fjs);}}(document,"script","twitter-wjs");</script>
            </div>
        </div>
    </div>
{% endblock %}

python_nigeria/templates/pinax/blog/dateline.html
<span class="text-muted post-meta">
    <span class="date">{% if post.published %}{{ post.published|date:"jS F Y" }}{% else %}Not published yet{% endif %}</span> /
    by <span class="author">{{ post.author.get_full_name }}</span> in
    <a href="{% url "pinax_blog:blog_section" post.section.slug %}"><span class="section">{{ post.section.name }}</span></a>
</span>

python_nigeria/templates/pinax/blog/dateline_stale.html
<p class="post-meta">
    {% if not post.stale %}
        <span class="date">{% if post.published %}{{ post.published|date:"jS F Y" }}{% else %}Not published yet{% endif %}</span> /
    {% endif %}
    by <span class="author">{{ post.author.get_full_name }}</span> in
    <a href="{% url "pinax_blog:blog_section" post.section.slug %}"><span class="section">{{ post.section.name }}</span></a>
</p>

python_nigeria/templates/pinax/blog/manage_post_create.html
{% extends "pinax/blog/manage_post_create.html" %}

python_nigeria/templates/pinax/blog/manage_post_list.html
{% extends "pinax/blog/blog_base.html" %}

{% block head_title_base %}{{ SITE_NAME }}{% endblock %}

{% block content %}
<a style="float:right;" class="btn btn-outline btn-primary" href="{% url 'pinax_blog:manage_post_create' %}">Create new post</a>
  {% if post_list %}
    <div class="post-list">
      {% for post in post_list %}
        <div class="post">          
          <h2><a href="{% url 'pinax_blog:manage_post_update' post.pk %}">{{ post.title }}</a></h2>
          {% include "pinax/blog/dateline.html" %}
          <div class="teaser">{{ post.teaser_html|safe }}</div>
          <!--<p class="more"><a href="{{ post.get_absolute_url }}" class="post-link">read more...</a></p>-->
          {% comment %} <div class="body-content"> {{post.content_html|safe}} </div> {% endcomment %}
        </div>
      {% endfor %}
    </div>
    {% include "pinax/pagination/builtin_pagination_reverse.html" %}
  {% else %}
    <p class="alert alert-info lead">No blog posts have been published.</p>
  {% endif %}
{% endblock %}

python_nigeria/templates/pinax/blog/manage_post_update.html
{% extends "pinax/blog/blog_base.html" %}
 {% load crispy_forms_tags %}
{% block head_title_base %}{{ SITE_NAME }}{% endblock %}

{% block content %}
<form method="POST" action="" enctype="multipart/form-data" class="form form-horizontal">
    {% csrf_token %} {{ form|crispy }}
    <div class="form-actions">
        <input class="btn btn-primary" type="submit" value="Upload" />
    </div>
</form>
{% endblock %}