config/urls.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.conf import settings
from django.conf.urls import include, url
from django.conf.urls.static import static
from django.contrib import admin
from django.views.generic import TemplateView, RedirectView
from symposion import views as symposion_views
from django.views import defaults as default_views
from . import views as o_views
from python_nigeria.core import views as core_views

urlpatterns = [
    # Examples:
    # url(r'^404$', TemplateView.as_view(template_name='500.html'), name='404'),
    # url(r'^blog/', include('blog.urls')),
    # url(r'^home/$', TemplateView.as_view(template_name='home.html'), name='home_page'),
    url(r"^design/home/$", core_views.DesignHomeView.as_view(), name="design_home"),
    url(r"^design/dashboard/$", core_views.DesignDashboardView.as_view(), name="design_dashboard_home"),
    url(r"^home/$", o_views.HomeRedirectView.as_view(), name="home_page"),
    # url(r'^schedule/$', o_views.ScheduleConferenceView.as_view(), name='schedule_conference'),
    url(r"^$", o_views.HomePage.as_view(), name="home"),
    url(r"^account/login/$", o_views.NewLoginView.as_view(), name="account_login"),
    url(
        r"^speaker/edit/(?:(?P<pk>\d+)/)?$",
        o_views.NewSpeakerEditView.as_view(),
        name="speaker_edit",
    ),
    url(r"^hijack/", include("hijack.urls")),
    url(r"^account/", include("account.urls")),
    url(r"^contact/", include("contact_form.urls")),
    # url(r'^captcha/', include('captcha.urls')),
    url(r"^we-are-allowed/", include(admin.site.urls)),
    url(r"^tickets/", include("python_nigeria.tickets.urls", namespace="tickets")),
    # url(r"^sponsorship/$", o_views.sponsors_view, name='sponsorship-proposal'),
]

if settings.DEBUG:
    # This allows the error pages to be debugged during development, just visit
    # these url in browser to see how these error pages look like.
    urlpatterns += [
        url(
            r"^400/$",
            default_views.bad_request,
            kwargs={"exception": Exception("Bad Request!")},
        ),
        url(
            r"^403/$",
            default_views.permission_denied,
            kwargs={"exception": Exception("Permission Denied")},
        ),
        url(
            r"^404/$",
            default_views.page_not_found,
            kwargs={"exception": Exception("Page not Found")},
        ),
        url(r"^500/$", default_views.server_error),
    ]
    import debug_toolbar

    urlpatterns += [url(r"^__debug__/", include(debug_toolbar.urls))]

urlpatterns += [
    # Your stuff: custom urls includes go here
    url(r"^dashboard/", o_views.dashboard, name="dashboard"),
    url(r"^proposals/", include("symposion.proposals.urls")),
    # url(r'^reviews/section/(?P<section_slug>[\w\-]+)/all/$', o_views.review_section, {"reviewed": "all"}, name="review_section"),
    url(r"^reviews/", include("symposion.reviews.urls")),
    url(r"^schedule/", include("symposion.schedule.urls")),
    url(r"^speaker/", include("symposion.speakers.urls")),
    url(r"^sponsors$", o_views.sponsors_list,name="sponsor_list"),
    url(r"^sponsors/apply", o_views.sponsor_apply, name="sponsor_apply"),
    url(r"^sponsors/", include("config.schedule_urls")),
    url(r"^teams/", include("symposion.teams.urls")),
    url(r"^boxes/", include("pinax.boxes.urls")),
    url(
        r"^blog/manage/posts/create/$",
        o_views.ManageCreatePost.as_view(),
        name="manage_post_create",
    ),
    url(
        r"^blog/manage/posts/(?P<post_pk>\d+)/update/$",
        o_views.ManageUpdatePost.as_view(),
        name="manage_post_update",
    ),
    url(r"^blog/", include("pinax.blog.urls", namespace="pinax_blog")),
    url(r"^", include("pinax.pages.urls")),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

python_nigeria/core/urls.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals
from django.views.decorators.csrf import csrf_exempt
import pytz
from django.conf.urls import include, url

from . import views

urlpatterns = [
    url(regex=r'online-payment/(?P<tutor_slug>[\w.@+-]+)/(?P<slug>[\w.@+-]+)/$',
        view=views.OnlinePaymentRedirectView.as_view(),
        name='dollar_online_payment'),
    url(regex=r'client-payment-completed/(?P<order>[\w.@+-]+)/$',
        view=csrf_exempt(views.ClientPaymentCompletedView.as_view()),
        name='request_complete_redirect'),
    url(regex=r'client-payment-cancelled/(?P<order>[\w.@+-]+)/$',
        view=csrf_exempt(views.FailedPaymentRedirectView.as_view()),
        name='request_cancelled_redirect'),
]

python_nigeria/tickets/urls.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.views.decorators.csrf import csrf_exempt
from django.conf import settings
from django.conf.urls import include, url
from django.contrib.auth.decorators import login_required
from . import views

urlpatterns = [
    # Examples:
    # url(r'^404$', TemplateView.as_view(template_name='500.html'), name='404'),
    # url(r'^blog/', include('blog.urls')),
    url(r"^$", views.TicketHomeView.as_view(), name="home"),
    url(r"^selected-plan$", views.intermediate_purchase, name="selected-plan"),
    url(r"^coupons$", views.valid_coupons, name="coupons"),
    url(
        r"^purchase/$",
        login_required(csrf_exempt(views.PurchaseView.as_view())),
        name="purchase",
    ),
    url(
        r"^purchase-complete/(?P<order>[\w.@+-]+)/$",
        login_required(views.purchase_complete),
        name="purchase-complete",
    ),
    # url(r'^checkout/(?P<order>[\w.@+-]+)/$', views.CheckoutView.as_view(), name='checkout_view'),
    # url(r'^checkout/(?P<order>[\w.@+-]+)/$', login_required(views.CheckoutView.as_view()), name='checkout_view'),
    url(
        r"^detail/(?P<order>[\w.@+-]+)/$",
        login_required(views.TicketDetailPage.as_view()),
        name="detail",
    ),
    url(
        r"^create/(?P<order>[\w.@+-]+)/$",
        login_required(views.CreateTicketview.as_view()),
        name="create_ticket",
    ),
    url(
        r"^sales/(?P<pk>\d+)/$",
        login_required(views.SalesTicketView.as_view()),
        name="sales",
    ),
    url(
        r"^paystack/webhook",
        view=csrf_exempt(views.paystack_webhook),
        name="p_stack_webhook",
    ),
    url(
        r"^paystack/callback/$",
        view=csrf_exempt(views.paystack_webhook),
        name="p_stack_callback",
    ),
    url(
        r"^paystack/callback/(?P<order>[\w.@+-]+)/$",
        view=csrf_exempt(views.PaystackCallBackView.as_view()),
        name="callback_paystack",
    ),
    url(
        r"^paystack/validate/(?P<order>[\w.@+-]+)/(?P<code>[\w.@+-]+)$",
        view=login_required(views.validate_paystack_ref),
        name="validate_paystack",
    ),
]

python_nigeria/core/models.py
from django.db import models
from symposion.sponsorship.models import Sponsor
class SponsorImage(models.Model):
    sponsor = models.OneToOneField(Sponsor, related_name='image_link')
    image = models.ImageField(upload_to="sponsors")

python_nigeria/proposals/models.py
from django.db import models
from django.utils.translation import ugettext_lazy as _
from markitup.fields import MarkupField
from symposion.proposals.models import ProposalBase


class Proposal(ProposalBase):

    AUDIENCE_LEVEL_NOVICE = 1
    AUDIENCE_LEVEL_EXPERIENCED = 2
    AUDIENCE_LEVEL_INTERMEDIATE = 3
    AUDIENCE_LEVEL_NOT_APPLICABLE = 4

    AUDIENCE_LEVELS = [
        (AUDIENCE_LEVEL_NOVICE, "Novice"),
        (AUDIENCE_LEVEL_INTERMEDIATE, "Intermediate or Advanced"),
        # (AUDIENCE_LEVEL_EXPERIENCED, "Experienced"),
        (AUDIENCE_LEVEL_NOT_APPLICABLE, "Not Applicable"),
    ]

    audience_level = models.IntegerField(choices=AUDIENCE_LEVELS)

    recording_release = models.BooleanField(
        default=True,
        help_text=_("By submitting your talk proposal, you agree to give "
                    "permission to the conference organizers to record, edit, "
                    "and release audio and/or video of your presentation. If "
                    "you do not agree to this, please uncheck this box."),
    )

    special_requirements = MarkupField(
        _("Special Requirements"),
        blank=True,
        help_text=_("If you have any special requirements such as needing "
                    "travel assistance, accessibility needs, or anything "
                    "else please let us know here so that  we may plan "
                    "accordingly. (This is not made public nor will the "
                    "review committee have access to view it.)")
    )

    class Meta:
        abstract = True

    def __unicode__(self):
        return u"%s" % self.title


class TalkProposal(Proposal):
    pass


class TutorialProposal(Proposal):
   pass


class OpenSpaceProposal(ProposalBase):
    pass

python_nigeria/proposals/forms.py
from django import forms
from markitup.widgets import MarkItUpWidget

from .models import OpenSpaceProposal, TalkProposal, TutorialProposal


class ProposalForm(forms.ModelForm):

    def clean_description(self):
        value = self.cleaned_data["description"]
        if len(value) > 400:
            raise forms.ValidationError(
                u"The description must be less than 400 characters"
            )
        return value

    def __init__(self, *args, **kwargs):
        super(ProposalForm, self).__init__(*args, **kwargs)
        for f in self.fields.values():
            if not f.required:
                continue
            f.widget.attrs.setdefault('required', True)
            f.label = '{} *'.format(f.label)


class OpenSpaceProposalForm(ProposalForm):

    class Meta:
        model = OpenSpaceProposal
        fields = [
            "title",
            "description",
            "abstract",
            "additional_notes",
        ]
        widgets = {
            "abstract": MarkItUpWidget(),
            "additional_notes": MarkItUpWidget(),
        }


class TalkProposalForm(ProposalForm):

    class Meta:
        model = TalkProposal
        fields = [
            "title",
            "audience_level",
            "description",
            "abstract",
            "additional_notes",
            "special_requirements",
            "recording_release",
        ]
        widgets = {
            "abstract": MarkItUpWidget(),
            "additional_notes": MarkItUpWidget(),
        }


class TutorialProposalForm(ProposalForm):

    class Meta:
        model = TutorialProposal
        fields = [
            "title",
            "audience_level",
            "description",
            "abstract",
            "additional_notes",
            "special_requirements",
            "recording_release",
        ]
        widgets = {
            "abstract": MarkItUpWidget(),
            "additional_notes": MarkItUpWidget(),
        }

python_nigeria/core/views.py
from django.contrib import messages
from django.views.generic import (
    FormView, RedirectView,
    TemplateView)
from config.utils import PayStack
import logging

logger = logging.getLogger(__name__)


class DesignDashboardView(TemplateView):
    template_name = "design/dashboard.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        return context


class DesignHomeView(TemplateView):
    template_name = "design/home.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context.update({
            'page_title': 'PyCon Nigeria 2025',
            'nav_items': [
                {'title': 'Home', 'url': '/', 'active': True},
                {'title': 'About', 'url': '/about/', 'has_dropdown': True},
                {'title': 'Schedule', 'url': '/schedule/', 'has_dropdown': True},
                {'title': 'Tickets', 'url': '/tickets/'},
                {'title': 'Contact', 'url': '/contact/'},
                {'title': 'Login', 'url': '/account/login/'},
            ]
        })
        return context


class OnlinePaymentRedirectView(RedirectView):
    permanent = False
    query_string = True

    def get_redirect_url(self, *args, **kwargs):
        try:
            req = services.SingleRequestService(slug=kwargs['slug'])
            url = req.create_online_booking(kwargs['tutor_slug'])
        except ObjectDoesNotExist:
            raise Http404('No Request matches the given query.')
        user = self.login_user(req.get_user())
        booking_url = "%s" % (reverse('request_payment_page', args=[url]),)

        if user is not None:
            return booking_url
        if self.request.user.is_authenticated():
            return booking_url
        return "%s?redirect_url=%s" % (reverse('account_login'), booking_url)

    def login_user(self, user):
        # log in the user
        user.backend = 'django.contrib.auth.backends.ModelBackend'
        login(self.request, user)
        return user


class ClientPaymentCompletedView(RedirectView):
    permanent = False
    query_string = True
    #

    def get_redirect_url(self, *args, **kwargs):
        status, message_txt = services.DepositMoneyService.generic_payment_outcome(
            self.request, **kwargs
        )
        if status:
            messages.info(self.request, message_txt)
            return reverse("users:revenue_transactions")
        messages.error(self.request, message_txt)
        return reverse("request_payment_page", args=[kwargs['order']])


class FailedPaymentRedirectView(RedirectView):
    permanent = False
    query_string = True

    def get_redirect_url(self, *args, **kwargs):
        print(self.request.POST)
        messages.error(self.request, "Sorry the payment was cancelled")
        return reverse('request_payment_page', args=[kwargs['order']])


class PaystackCallBackView(RedirectView):
    permanent = False
    query_string = True

    def get_redirect_url(self, *args, **kwargs):
        x = self.request.POST
        logger.info(x)
        print(x)
        y = self.request.GET.get('trxref')
        if y:
            v = utils.PayStack().validate_transaction(y)
            if v:
                try:
                    d = services.DepositMoneyService(kwargs.get('order'))
                    d.notify_admin_of_payments_made(condition=True, **v)
                    messages.info(
                        self.request, "Transaction Payment Successful!")
                    return reverse('users:revenue_transactions')
                except ObjectDoesNotExist:
                    d = services.SingleRequestService(kwargs.get('order'))
                    d.pay_processing_fee()
                    messages.info(
                        self.request, "Processing Fee Payment Successful!")
                    return reverse('processing_fee_completed', args=[kwargs.get('order')])
        messages.error(
            self.request, "Sorry there was an error in this transaction. contact info@tuteria.com")
        return reverse('request_payment_page', args=[kwargs.get('order')])

python_nigeria/templates/tickets/create.html
{% extends "symposion/speakers/base.html" %}
{% load add_attr %}
{% load crispy_forms_tags %}
{% load i18n %}
{% load pinax_boxes_tags %}
{% load static from staticfiles %}

{% block page_title %}{% trans "Create Ticket Detail" %}{% endblock %}

{% block body %}
<div class="small-header poster-wrapper">
  <h1>{% trans "Create Ticket Detail" %}</h1>
</div>

<div class="poster-wrapper">
  <div class="container">
    <div class="row">
        <div  class="col-md-6 col-md-offset-3">
        {% box "ticket-create" %}

        <form method="POST" action="" enctype="multipart/form-data">
            {% csrf_token %}
            <legend>{% trans "Create Ticket" %}</legend>
            
                    <div class="control-group  field textinput charfield">
                      <label class="control-label" for="id_t4446-tagline">Full Name</label>
                      <div class="controls">
                        {{ticket_form.full_name|add_attributes:"class:form-control"}}
                      </div>
                    </div>

                    <div class="control-group  field textinput charfield">
                      <label class="control-label" for="id_t4446-tagline">Tagline</label>
                      <div class="controls">
                        {{ticket_form.tagline|add_attributes:"class:form-control"}}
                        <span class="help-block">a (funny?) tagline that will be displayed on the badge<br>Eg. CEO of FooBar Inc.; Super Python fanboy; Simple is better than complex.</span>
                      </div>
                    </div>

                    <div class="control-group  field select typedchoicefield">
                      <label class="control-label" for="id_t4446-diet">Diet <span>(required)</span></label>
                      <div class="controls">
                        {{ticket_form.diet|add_attributes:"class:form-control"}}

                      </div>
                    </div>
                    <br />
            <div class="form-actions">
                <input class="btn btn-primary" type="submit" value="Save" />
            </div>
        </form>
        </div>
    </div>
  </div>
</div>
{% endblock %}

python_nigeria/templates/tickets/home.html
{% extends "apply.html" %} 
{% load static pinax_boxes_tags %}
{% load static from staticfiles %} 
{% load pinax_boxes_tags %} 
{% block head_title %} Ticket Page | {% endblock head_title %}
{% block extra_stylings %} {{block.super}}
<style>
 .ticket-category img{
   width: 60%;
 }
 .ticket-category img.individual{
   width: 90%;
 }
 .ticket-category p.notice{
   margin: 0;
 }
 .ticket-category p.notice+.price{
   margin-top: 20px;
 }
 .ticket-category img + p{
   padding: 24px;
 }
 .ticket-category .link-button{
  padding: 15px !important; width: 100%;
 }
 @media(max-width: 768px){
   .ticket-category{
     margin-bottom: 20px;
   }
 }
@media (min-width: 992px){
#navbar.home + #header-section, #navbar.home + #speakers-section, #navbar.home + #purchase-tickets-section, #navbar.home + #code-of-conduct-section, #navbar.home + .custom-image-section {
        margin-top: -120px;
    padding-top: 80px;
    height: 500px !important;
}}
</style>
{% endblock extra_stylings %}

{% block hero_label %}
{% box 'ticket_home_label' %}
{% endblock %}
{% block hero_title %}
{% box 'ticket_home_title' %}
{% endblock %}
{% block hero_subtitle %}
{% box 'ticket_home_subtitle' %}
{% endblock %}


 {% block content %}
 {% box 'ticket_home_alert' %}


<div class="packages row text-center  pt-5 mb-4">
    {% for plan in plans %}
    <div class="col-sm-12 col-md-3">
      <div class="ticket-category">
        <h6>{{plan.name|upper}}</h6>
        <img src="{{plan.url}}" class="{{plan.style}}" />
        <p>{{plan.description}}</p>
        
        {% if plan.early_bird %}
        <h3 class="price strike">N{{plan.amount}}</h3>
        <p class="notice">Early Bird</p>
  
        <h3 class="price">N{{plan.early_price}}</h3>
        
        {% else %}
        <h3 class="price strike">N{{plan.early_price}}</h3>
        <p class="notice">Price</p>
        <h3 class="price">N{{plan.amount}}</h3>
        {% endif %}
  {% if plan.current_price  %}
  <a href="{% url 'tickets:selected-plan' %}?selected_plan={{plan.short_name}}" class="link-button btn btn-success buy-tickets-button">BUY TICKETS</a>
  
  {% else %}
  <span style="color: white !important;" class="link-button btn btn-danger buy-tickets-button">SOLD OUT</span>

  {% endif %}
      </div>
    </div>
    {% endfor %}
</div>

{% box 'ticket_home_payment_footer_alert' %}

{% box 'ticket_home_value_heading' %}

  {% box 'ticket_home_value_description' %}

<br />
<br />
<br />
<br /> {% endblock %}

python_nigeria/templates/tickets/purchase-complete.html
{% extends "apply.html" %} {% load static pinax_boxes_tags %} 
{% load static from staticfiles %} 
{% load pinax_boxes_tags %} 
{% block navigation %}

{% endblock  %}
{% block sidebar-counter %} {% endblock sidebar-counter %} 
{% block content %} {% endblock content %}
{% block messages %} {% endblock messages %}
{% block header-section %}
 <div class="main-content container">
            {% if messages %}
                {% for message in messages %}
                <div class="alert {% if message.tags %}alert-{{ message.tags }}{% endif %}">{{ message }}</div>
                {% endfor %}
            {% endif %} 
            
        </div>
<div id="tickets-complete-section" class="jumbotron jumbotron-fluid">

  <div class="container">
    <div class="row">
      <div class="col-md-6">
        <img class="logo" src="{% static 'designs/dist/pycon2024.svg' %}" alt="pyconng logo" />

        <div class="tickets">
          <p>>>> Ticket purchase complete</p>

          <img src="{% static 'designs/img/purchase-tickets-complete/ticket-icon.svg' %}" alt="tickets">
        </div>
        {% box "ticket_complete_message" %}
        

        <hr>

        <div class="social-share">

          
          {% box 'ticket_social_heading' %}

          {% box 'ticket_social_detail' %}
        </div>
        <div class="tickets-order">
          <h3>Your order has been received:</h3>
          <ol>
            <li> Order
              <span>#{{ticket.pk}}</span> {{count}} tickets of &#8358;{{ticket.total_amount}}
            </li>
            {% if ticket.created_tickets %}
            <li> Click
              <a href="{% url 'tickets:detail' ticket.pk %}">Here</a> to view your tickets
            </li>
            {% else %}
            <li> Click <a href="{% url 'tickets:create_ticket' ticket.pk %}">Here</a> to create your tickets </li>
            {% endif %}
          </ol>
        </div>
      </div>
      <div class="col-md-5 offset-md-1 d-none d-sm-block">
<img src="{% static 'designs/img/purchase-tickets-complete/pythonista-party.svg' %}" alt="pythonista party" />
      </div>
    </div>
  </div>
</div>
<div class="copyright">
  <p class="text-center">COPYRIGHT 2024. PYCON NIGERIA 2024</p>
</div>
{% endblock header-section %}
{% comment %} <extends src="./base.html">

  <body>
    <block name="title">Purchase Tickets - Complete</block>

    <block name="navigation"></block>

    <block name="header-section">

    </block>
  </body>
  <block name="footer">

  </block>

</extends> {% endcomment %}
{% block footer %}

{% endblock footer %}

python_nigeria/templates/tickets/purchase.html
{% extends "apply.html" %} {% load static pinax_boxes_tags %} 
{% load static from staticfiles %} 
{% load pinax_boxes_tags %} 
{% block navigation %} 
{% endblock %} {% block head_title %} Purchase Ticket | 
{% endblock head_title %} 
{% block extra_stylings %} {{block.super}}
<style>
  @media (min-width: 992px) {
    #navbar.home+#header-section,
    #navbar.home+#speakers-section,
    #navbar.home+#purchase-tickets-section,
    #navbar.home+#code-of-conduct-section,
    #navbar.home+.custom-image-section {
      margin-top: -120px;
      padding-top: 80px;
      height: 500px !important;
    }
  }
  .hide-section{
    display: none !important;
  }
  .show-section{
    display: block;
  }
  .form-content p {
    margin-top: 0;
}
strong#ticket-count, strong#total-fee{
  font-size: 25px;
}
.coupon-code{
  display: flex;
}
.coupon-code button{
  padding: 0 30px !important;
  cursor: pointer;
}
.discount_value{
  display: flex;
 justify-content: space-between;
}
</style>
{% endblock extra_stylings %} {% block header-section %} {% comment %}
<div id="header-section" class="jumbotron jumbotron-fluid">
  {% box "home_introduction" %} {% endcomment %}
  <div id="purchase-tickets-section" class="ticket-section jumbotron jumbotron-fluid">
    <div class="container">
      <div class="row">
        <div class="col-md-5">
          <img class="logo" src="{% static 'designs/dist/pycon2024.svg' %}" />
          <div class="hide-mobile">
            {% box "purchase_label" %}
            {% box "purchase_title" %}
            {% box "purchase_subtitle" %}
            
            
            

          </div>
        </div>

        <div class="col-md-5 offset-md-2">
          <div class="form-content">
            <ul class="nav nav-tabs nav-justified" id="myTab" role="tablist">
              <li class="nav-item">
                <a class="nav-link active" data-toggle="tab" href="#personal-info" role="tab" aria-selected="true">1. PERSONAL INFO</a>
              </li>
              <li class="nav-item">
                <a id="payment-link" class="nav-link" data-toggle="tab" href="#make-payment" role="tab" aria-selected="false">2. MAKE PAYMENT</a>
              </li>
            </ul>

            <div class="tab-content">
              <div class="tab-pane fade show active" id="personal-info" role="tabpanel">
                <div>
                  {% with user=request.user %}
                  <div id="error-section" class="hide-section alert alert-warning password-alert" role="alert">
                    Please ensure you fill out all the fields.
                  </div>
                  <div class="form-group">
                    <label for="first_name">pythonista.first_name</label>
                    <input type="text" class="form-control" id="first_name" value="{{user.first_name}}" placeholder="Enter your first name here"
                      required>
                  </div>
                  <div class="form-group">
                    <label for="last_name">pythonista.last_name</label>
                    <input type="text" value="{{user.last_name}}" class="form-control" id="last_name" placeholder="Enter your last name here"
                      required>
                  </div>
                  <div class="form-group">
                    <label for="email">pythonista.email</label>
                    <input type="text" class="form-control" value="{{user.email}}" id="email" placeholder="Enter your email address here" required>
                  </div>

                  {% endwith %} {% comment %}
                  <div class="alert alert-warning password-alert" role="alert">
                    By providing a password, you’ll get access to speaker keynotes and development resources.
                  </div>

                  <div class="form-group">
                    <label for="password">pythonista.password</label>
                    <input type="password" class="form-control" id="password" placeholder="Enter that hashed password here :-)" required>
                  </div> {% endcomment %}
                  <form>
                    <button id="toStep2" class="link-button btn btn-block btn-success">CONTINUE TO STEP 2.</a>
                    <script src="https://js.paystack.co/v1/inline.js"></script>
                  </form>
                  </div>
              </div>

              <div class="tab-pane fade" id="make-payment" role="tabpanel">
                <form>
                  <ul class="container">
                    {% for ticket in tickets %}
                    <li id="{{ticket.short_name}}" class="row ticket-select">
                      <div class="col-sm-9">
                        <p>{{ticket.name}}</p>
                        <span>N{{ticket.amount}}</span>
                      </div>
                      <div class="col-sm-3">
<select value="">
                          <option>0</option>
                          <option {% if default_plan == ticket.short_name %}selected{% endif %}>1</option>
                          <option>2</option>
                          <option>3</option>
                          <option>4</option>
                          <option>5</option>
                        </select>
                      </div>
                    </li>

                    {% endfor %}
                  </ul>

                  <p id="initiate-discount">Have a discount code?
                    <a style="cursor: pointer;">Click here</a>
                  </p>
                  <div class="form-group discount_value hide-section">
                    <p>Discount</p>
                    <p ><span id="percent-value">0</span>%</p>
                  </div>
                <div class="form-group coupon-code hide-section">
                  <input type="text" class="form-control" id="coupon_value" value="" placeholder="Input coupon code" >
                  <button id="code_btn" class="btn btn-primary">Validate code</button>
                </div>
                <div class="form-group"> 
                  <div id="div_id_recording_release" class="checkbox"> 
                    <label for="coc_confirm" class=""> 
<input type="checkbox" style="height: auto;" id="coc_confirm" name="code_of_conduct_confirm" class="checkboxinput" >
                      Code of Conduct
                </label> <p id="hint_id_recording_release" class="help-block">By purchasing a ticket, you agree to abide by every rule indicated in the Pycon Nigeria Code of Conduct.</p> </div> </div>
                  <button type="submit" id="pstackButton" disabled class="btn btn-block btn-success">CHECKOUT</button>

                  <div id="tickets-summary" class="row">
                    <p class="col-sm-12 col-md-4">QTY: <strong id="ticket-count"></span></strong>
                    <p class="col-sm -12 col-md-8 total-fee">TOTAL FEE: N<strong id="total-fee">0</strong></p>
                  </div>

                  <div id="tickets-payment-option" class="row">
                    <div class="col-sm-12 text-center">
                      Verve, MasterCard, Visa
                    </div>
                  </div>
                </form>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
  <div class="copyright">
    <p class="text-center">COPYRIGHT 2017. PYCON NIGERIA 2018</p>
  </div>
  {% comment %}
  <div class="container-fluid">

  </div>
</div> {% endcomment %} {% endblock %} {% block content %} {% endblock %} {% block footer %} {% endblock %} {% block js_script %}
<script>
  window.INITIALIZER = {
    pricings:{},
    public_key: "{{public_key}}",
    purchase_url: "{% url 'tickets:purchase' %}",
 coupon_url: "{% url 'tickets:coupons' %}"
  }
  {% for ticket in tickets %}
  window.INITIALIZER.pricings["{{ticket.short_name}}"] = {{ticket.amount}}
  {% endfor %}
</script>
<script src="{% static "js/purchase.js" %}"></script>
{% endblock js_script %}